const actionTaskList = {
  CREATE_TASK: 'CREATE_TASK',
  EDIT_TASK: 'EDIT_TASK',
  DELETE_TASK: 'DELETE_TASK',
  DRAFT_TO_PUBLISHED: 'DRAFT_TO_PUBLISHED',
  PUBLISHED_TO_DRAFT: 'PUBLISHED_TO_DRAFT',
  PUBLISHED_TO_ARCHIVED: 'PUBLISHED_TO_ARCHIVED',
  ARCHIVED_TO_PUBLISHED: 'ARCHIVED_TO_PUBLISHED',
};

const actionRevReqList = {
  CREATE_REVREQ: 'CREATE_REVREQ',
  EDIT_REVREQ: 'EDIT_REVREQ',
  DELETE_REVREQ: 'DELETE_REVREQ',
  DRAFT_TO_PUBLISHED: 'DRAFT_TO_PUBLISHED',
  PUBLISHED_TO_DRAFT: 'PUBLISHED_TO_DRAFT',
  PUBLISHED_TO_COMPLETED: 'PUBLISHED_TO_COMPLETED',
  COMPLETED_TO_PUBLISHED: 'COMPLETED_TO_PUBLISHED',
};

const actionCCSessionCheckList = {
  CREATE_CROSSCHECK: 'CREATE_CROSSCHECK',
  EDIT_CROSSCHECK: 'EDIT_CROSSCHECK',
  DELETE_CROSSCHECK: 'DELETE_CROSSCHECK',
  DRAFT_TO_REQUESTS_GATHERING: 'DRAFT_TO_REQUESTS_GATHERING',
  REQUESTS_GATHERING_TO_CROSS_CHECK: 'REQUESTS_GATHERING_TO_CROSS_CHECK',
  CROSS_CHECK_TO_COMPLETED: 'CROSS_CHECK_TO_COMPLETED',
};

export { actionTaskList, actionRevReqList, actionCCSessionCheckList };
