const actionTaskList = {
  CREATE_TASK: 'CREATE_TASK',
  EDIT_TASK: 'EDIT_TASK',
  DELETE_TASK: 'DELETE_TASK',
  DRAFT_TO_PUBLISHED: 'DRAFT_TO_PUBLISHED',
  PUBLISHED_TO_DRAFT: 'PUBLISHED_TO_DRAFT',
  PUBLISHED_TO_ARCHIVED: 'PUBLISHED_TO_ARCHIVED',
  ARCHIVED_TO_PUBLISHED: 'ARCHIVED_TO_PUBLISHED',
};

export default actionTaskList;
