const actionTaskList = {
  CREATE_TASK: 'CREATE_TASK',
  EDIT_TASK: 'EDIT_TASK',
  DELETE_TASK: 'DELETE_TASK',
  DRAFT_TO_PUBLISHED: 'DRAFT_TO_PUBLISHED',
  PUBLISHED_TO_DRAFT: 'PUBLISHED_TO_DRAFT',
  PUBLISHED_TO_ARCHIVED: 'PUBLISHED_TO_ARCHIVED',
  ARCHIVED_TO_PUBLISHED: 'ARCHIVED_TO_PUBLISHED',
};

const actionRevReqList = {
  CREATE_REVREQ: 'CREATE_REVREQ',
  EDIT_REVREQ: 'EDIT_REVREQ',
  DELETE_REVREQ: 'DELETE_REVREQ',
  DRAFT_TO_PUBLISHED: 'DRAFT_TO_PUBLISHED',
  PUBLISHED_TO_DRAFT: 'PUBLISHED_TO_DRAFT',
  PUBLISHED_TO_COMPLETED: 'PUBLISHED_TO_COMPLETED',
  COMPLETED_TO_PUBLISHED: 'COMPLETED_TO_PUBLISHED',
};

export { actionTaskList, actionRevReqList };
