export const EDITORS = {
  DISPLAY_ONLY: 'DISPLAY_ONLY',
  REVIEWER: 'REVIEWER',
  STUDENT: 'STUDENT',
};

export const REVIEW_STATE = {
  DRAFT: 'DRAFT',
  PUBLISHED: 'PUBLISHED',
  ACCEPTED: 'ACCEPTED',
  DISPUTED: 'DISPUTED',
};
