const defaultRowsByPage = 10;
const defaultCustomers = [
  {
    id: 1,
    crossCheckSessionId: null,
    author: 'Виталий',
    task: 'Songbird',
    state: 'COMPLETED',
    selfGrade: 176,
  },
  {
    id: 2,
    crossCheckSessionId: null,
    author: 'Андрей',
    task: 'Songbird',
    state: 'COMPLETED',
    selfGrade: 180,
  },
  {
    id: 3,
    crossCheckSessionId: null,
    author: 'Константин',
    task: 'Schedule',
    state: 'PUBLISHED',
    selfGrade: 165,
  },
  {
    id: 4,
    crossCheckSessionId: null,
    author: 'Елена',
    task: 'Schedule',
    state: 'DRAFT',
    selfGrade: 150,
  },
  {
    id: 5,
    crossCheckSessionId: null,
    author: 'Василий',
    task: 'Singolo',
    state: 'COMPLETED',
    selfGrade: 189,
  },
  {
    id: 6,
    crossCheckSessionId: null,
    author: 'Екатерина',
    task: 'Singolo',
    state: 'COMPLETED',
    selfGrade: 220,
  },
  {
    id: 7,
    crossCheckSessionId: null,
    author: 'Александр',
    task: 'Singolo',
    state: 'COMPLETED',
    selfGrade: 205,
  },
  {
    id: 8,
    crossCheckSessionId: null,
    author: 'Анатолий',
    task: 'Singolo',
    state: 'COMPLETED',
    selfGrade: 140,
  },
  {
    id: 9,
    crossCheckSessionId: null,
    author: 'Яна',
    task: 'SpeakIt',
    state: 'DRAFT',
    selfGrade: 154,
  },
  {
    id: 10,
    crossCheckSessionId: null,
    author: 'Ольга',
    task: 'MovieSearch',
    state: 'PUBLISHED',
    selfGrade: 245,
  },
  {
    id: 11,
    crossCheckSessionId: null,
    author: 'Дарья',
    task: 'MovieSearch',
    state: 'PUBLISHED',
    selfGrade: 250,
  },
  {
    id: 12,
    crossCheckSessionId: null,
    author: 'Анатолий',
    task: 'MovieSearch',
    state: 'PUBLISHED',
    selfGrade: 210,
  },
  {
    id: 13,
    crossCheckSessionId: null,
    author: 'Руслан',
    task: 'RS Lang',
    state: 'DRAFT',
    selfGrade: 202,
  },
  {
    id: 14,
    crossCheckSessionId: null,
    author: 'Анатолий',
    task: 'RS Lang',
    state: 'DRAFT',
    selfGrade: 176,
  },
  {
    id: 15,
    crossCheckSessionId: null,
    author: 'Яна',
    task: 'RS Lang',
    state: 'DRAFT',
    selfGrade: 190,
  },
];

const tableColumns = [
  {
    title: 'ID',
    dataIndex: 'id',
    key: 'id',
    isSearchable: false,
  },
  {
    title: 'crossCheckID',
    dataIndex: 'crossCheckID',
    key: 'crossCheckID',
    isSearchable: false,
  },
  {
    title: 'Author',
    dataIndex: 'author',
    key: 'author',
    isSearchable: true,
  },
  {
    title: 'Task',
    dataIndex: 'task',
    key: 'task',
    isSearchable: true,
  },
  {
    title: 'Status',
    dataIndex: 'state',
    key: 'state',
    isSearchable: false,
    filters: [
      {
        text: 'DRAFT',
        value: 'DRAFT',
      },
      {
        text: 'PUBLISHED',
        value: 'PUBLISHED',
      },
      {
        text: 'COMPLETED',
        value: 'COMPLETED',
      },
    ],
    onFilter: (value, record) => record.state.indexOf(value) === 0,
  },
  {
    title: 'SelfGrade',
    dataIndex: 'selfGrade',
    key: 'selfGrade',
    isSearchable: false,
    sorter: (a, b) => a.selfGrade - b.selfGrade,
  },
];

const pagination = {
  showSizeChanger: true,
  defaultPageSize: defaultRowsByPage,
  defaultCurrent: 1,
};

export { defaultRowsByPage, defaultCustomers, tableColumns, pagination };
