name: Docker Image CI

on:
  push:
    branches: [ dev, master ]
  pull_request:
    branches: [ dev, master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag x-check-app:$(date +%s)
    - name: Push to Dockerhub
      run: docker push loremipsum666/x-check-app
